FONT_SIZE     = 7
FONT_STYLE    = "font-size:"+str(FONT_SIZE)+"px; font-family:Arial"
IMG_SIZE      = (600, 120)

SQUARE_SIZE   = 80
SQUARE_STROKE = 2
SQ_TEXT_OFFSET = 10
SQUARE_OFFSET = 25
LEFT_OFFSET   = SQUARE_SIZE/5
TOP_OFFSET    = SQUARE_SIZE/5

LINE_STROKE   = 1
LINE_TEXT_OFFSET = SQUARE_SIZE/20

CIRCLE_RADIUS = 10
CIRCLE_STROKE = 1